/*

        
    ------------------
        USUARIOS
    ------------------

    1 - 

    --------------------
        PROPRIEDADES
    --------------------

    1 - VOU DEIXAR SEM VERIFICAR SE O USUÁRIO ESTA DESATIVADO NAS PROPRIEDADES
        obs:teoricamente não tem como ele logar se ta desativado, logo  elle não posue token
        BUG - SE O USUÁRIO TIVER LOGADO E FOR REMOVIDO DA PROPRIEDADE ELE E CONSEGUE FAZER ALTERAÇÕES
    

*/